### PR TITLE
UX: Made apply button instantly visible

### LINKED ISSUE #4: make it easier to apply to hackgt with a clearer UI
probably just add the button on the 'about' section of the page, or similar

### PR DESCRIPTION
**Pull request by mjkaufer**
Also mobile-optimized some text, and store whether or not user has seen 'init' message in localstorage

Should fix https://github.com/HackGT/hackgt4/issues/4

### CODE REVIEW

**Comment by illegalprime** [comment]
I think we should keep `package-lock.json` it lets us know what package versions work with this app for sure.

**Comment by mjkaufer** [comment]
@illegalprime isn't that what versioning in the `package.json` is for?

**Comment by illegalprime** [comment]
@mjkaufer yeah it is, `package.json` says what versions our app _should_ work with but `package-lock.json` shows us one combination of packages that worked _for sure_.

**Comment by mjkaufer** [comment]
@illegalprime Sounds good, re-added it

**Comment by illegalprime** [comment]
Just to add another thing, for libraries `package.json` should be ignored, since you want your library to work with all versions stated in your `package.json`, for applications or binaries you should have a `package-lock.json`

**Comment by bunsenmcdubbs** [comment]
UI bug before initial animation is complete - `Apply Now` button overlaps with `Skip...`
screen shot 2017-08-08 at 1 14 43 pm

**Review by bunsenmcdubbs — CHANGES_REQUESTED** [review]
see UI bug comment

**Comment by mjkaufer** [comment]
@bunsenmcdubbs I think I fixed the skip bug

**Comment by illegalprime** [comment]
testing...

**Comment by bunsenmcdubbs** [comment]
Is there no more intro sequence? I can't seem to find it (checked localStorage - nothing there - and still don't see any intro/skip button)

**Comment by mjkaufer** [comment]
@bunsenmcdubbs I'm definitely getting it on my end - try it in an incognito window or something. If that still doesn't work, give me your browser details.

**Comment by bunsenmcdubbs** [comment]
@mjkaufer the skip button and apply now are still overlapping when the window is large

**Comment by mjkaufer** [comment]
@bunsenmcdubbs I'm not seeing anything like that on my end. Did you try re-bundling everything? Also, can you let me know screen resolution + browser + OS?

**Comment by illegalprime** [comment]
@mjkaufer add ` text-decoration: none;`

**Review by bunsenmcdubbs — APPROVED** [review]

**Pull request merged**
